name: Build zip

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the source code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          coverage: none

      - name: Set up Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install and build React app
        working-directory: ./plugin-dir/react
        run: |
          npm ci
          npm run build

      - name: Clean up react directory (keep only build/)
        run: |
          find ./plugin-dir/react -mindepth 1 -not -name build -exec rm -rf {} +

      - name: Install Composer dependencies
        working-directory: ./plugin-dir
        run: |
          composer install --no-dev --optimize-autoloader
        env:
          COMPOSER_ROOT_VERSION: 1.0.0

      - name: Remove all files and directories except plugin directory
        run: |
          find . -mindepth 1 -maxdepth 1 -not -name 'plugin-dir' -exec rm -rf {} +
          mv plugin-dir cf7-telegram

      - name: Zip the plugin directory
        run: zip -r cf7-telegram-wp-plugin.zip cf7-telegram

      - name: Upload Release Artifact
        uses: AButler/upload-release-assets@v3.0
        with:
          files: ./cf7-telegram-wp-plugin.zip
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to plugin-dist branch
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # Сохраняем текущий путь
          export TEMP_DIR=$(mktemp -d)
          cp -r cf7-telegram/* "$TEMP_DIR/"

          # Получаем ветку plugin-dist как отдельный чистый clone
          git fetch origin plugin-dist || true
          git worktree add --force dist-worktree origin/plugin-dist

          # Очищаем ветку полностью
          rm -rf dist-worktree/*
          cp -r "$TEMP_DIR/"* dist-worktree/

          cd dist-worktree
          git add .
          git commit -m "Update plugin build from release ${{ github.event.release.tag_name }}" || echo "No changes to commit"
          git push origin HEAD:plugin-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

