name: Build zip
on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the source code
        uses: actions/checkout@v3

      - uses: shivammathur/setup-php@v2
        name: Set up PHP
        with:
          php-version: 8.2
          coverage: none

      - name: Remove all files and directories except plugin directory
        run: |
          find . -mindepth 1 -maxdepth 1 -not -name 'plugin-dir' -exec rm -rf {} +
          rm -fr plugin-dir/lib plugin-dir/react
          mv plugin-dir cf7-telegram

      - name: Upload Release Artifact
        uses: AButler/upload-release-assets@v3.0
        with:
          files: ./cf7-telegram-wp-plugin.zip
          repo-token: ${{ secrets.GITHUB_TOKEN }}